# -*- coding: utf-8 -*-
"""makaleNLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_88zmh5DXFUWidvavvRpAW0x1R-zDrC
"""

import pandas as pd
from transformers import pipeline

# Örnek verilerle dataframe oluşturma
data = {
    'comment': [
        'Otel çok güzeldi, hizmet harikaydı.',
        'Oda kirliydi ve hizmet kötüydü.',
        'Otel ortalama, ne iyi ne kötü.'
    ]
}
df = pd.DataFrame(data)

# Zero-shot classification pipeline with a model supporting Turkish
classifier = pipeline('zero-shot-classification', model='joeddav/xlm-roberta-large-xnli')

# Kategori adayları (Türkçe)
candidate_labels = ['olumlu', 'olumsuz', 'tarafsız']

# Yorumları analiz et ve etiketle
df['sentiment'] = df['comment'].apply(lambda x: classifier(x, candidate_labels)['labels'][0])

print(df)

cls=pipeline("sentiment-analysis")

# Yorumları analiz eden ve hem etiket hem de skoru döndüren fonksiyon
def analyze_sentiment(comment):
    result = classifier(comment, candidate_labels)
    label = result['labels'][0]
    score = result['scores'][0]
    return label, score

# Yorumları analiz et ve dataframe'e ekle
df['sentiment'], df['score'] = zip(*df['comment'].apply(analyze_sentiment))

print(df)